
# final stage
FROM debian:stable-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN update-ca-certificates
COPY bin/* /usr/local/bin/

# Non-root user
RUN useradd -r -s /bin/false buildoor
USER buildoor

EXPOSE 9000
ENTRYPOINT ["buildoor"]
CMD ["run"]
