// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b88f4577f809d21495b23ade5b57ee353a8cb5f9310f34f1e02e865c3ed09955
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package types

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BuilderPreferencesV1 to SSZ-encoded bytes.
func (t *BuilderPreferencesV1) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderPreferencesV1 to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderPreferencesV1) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderPreferencesV1)
	}
	{ // Static Field #0 'MaxExecutionPayment'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.MaxExecutionPayment))
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderPreferencesV1 from SSZ-encoded bytes.
func (t *BuilderPreferencesV1) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	{ // Field #0 'MaxExecutionPayment' (static)
		buf := buf[0:8]
		t.MaxExecutionPayment = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderPreferencesV1.
func (t *BuilderPreferencesV1) SizeSSZ() (size int) {
	return 8
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderPreferencesV1.
func (t *BuilderPreferencesV1) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BuilderPreferencesV1 using the given hash walker.
func (t *BuilderPreferencesV1) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderPreferencesV1)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'MaxExecutionPayment'
		hh.PutUint64(uint64(t.MaxExecutionPayment))
	}
	hh.Merkleize(idx)
	return nil
}
