// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 9f904955a5e5d816ee1b4502c2aaaf43b2f6f381e3624e3e2989ec0ca423355d
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package types

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/all"
	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/holiman/uint256"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*BuilderBidBellatrix](`ssz-static:"false"`)
var _ = sszutils.Annotate[*BuilderBidCapella](`ssz-static:"false"`)
var _ = sszutils.Annotate[*BuilderBidDeneb](`ssz-static:"false"`)
var _ = sszutils.Annotate[*BuilderBidElectra](`ssz-static:"false"`)

func (t *BuilderBid) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *BuilderBidBellatrix:
		return t.marshalSSZView_BuilderBidBellatrix
	case *BuilderBidCapella:
		return t.marshalSSZView_BuilderBidCapella
	case *BuilderBidDeneb:
		return t.marshalSSZView_BuilderBidDeneb
	case *BuilderBidElectra:
		return t.marshalSSZView_BuilderBidElectra
	}
	return nil
}
func (t *BuilderBid) marshalSSZView_BuilderBidBellatrix(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Header'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #2 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Dynamic Field #0 'Header'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		dstlen := len(dst)
		{ // Static Field #0 'ParentHash'
			dst = append(dst, t.ParentHash[:32]...)
		}
		{ // Static Field #1 'FeeRecipient'
			dst = append(dst, t.FeeRecipient[:20]...)
		}
		{ // Static Field #2 'StateRoot'
			dst = append(dst, t.StateRoot[:32]...)
		}
		{ // Static Field #3 'ReceiptsRoot'
			dst = append(dst, t.ReceiptsRoot[:32]...)
		}
		{ // Static Field #4 'LogsBloom'
			dst = append(dst, t.LogsBloom[:256]...)
		}
		{ // Static Field #5 'PrevRandao'
			dst = append(dst, t.PrevRandao[:32]...)
		}
		{ // Static Field #6 'BlockNumber'
			dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
		}
		{ // Static Field #7 'GasLimit'
			dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
		}
		{ // Static Field #8 'GasUsed'
			dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
		}
		{ // Static Field #9 'Timestamp'
			dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
		}
		// Offset Field #10 'ExtraData'
		dst = append(dst, 0, 0, 0, 0)
		{ // Static Field #11 'BaseFeePerGasLE'
			dst = append(dst, t.BaseFeePerGasLE[:32]...)
		}
		{ // Static Field #12 'BlockHash'
			dst = append(dst, t.BlockHash[:32]...)
		}
		{ // Static Field #13 'TransactionsRoot'
			dst = append(dst, t.TransactionsRoot[:32]...)
		}
		{ // Dynamic Field #10 'ExtraData'
			binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
			vlen := len(t.ExtraData)
			if vlen > 32 {
				return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "Header.ExtraData")
			}
			dst = append(dst, t.ExtraData[:]...)
		}
	}
	return dst, nil
}

func (t *BuilderBid) marshalSSZView_BuilderBidCapella(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Header'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #2 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Dynamic Field #0 'Header'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		dstlen := len(dst)
		{ // Static Field #0 'ParentHash'
			dst = append(dst, t.ParentHash[:32]...)
		}
		{ // Static Field #1 'FeeRecipient'
			dst = append(dst, t.FeeRecipient[:20]...)
		}
		{ // Static Field #2 'StateRoot'
			dst = append(dst, t.StateRoot[:32]...)
		}
		{ // Static Field #3 'ReceiptsRoot'
			dst = append(dst, t.ReceiptsRoot[:32]...)
		}
		{ // Static Field #4 'LogsBloom'
			dst = append(dst, t.LogsBloom[:256]...)
		}
		{ // Static Field #5 'PrevRandao'
			dst = append(dst, t.PrevRandao[:32]...)
		}
		{ // Static Field #6 'BlockNumber'
			dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
		}
		{ // Static Field #7 'GasLimit'
			dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
		}
		{ // Static Field #8 'GasUsed'
			dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
		}
		{ // Static Field #9 'Timestamp'
			dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
		}
		// Offset Field #10 'ExtraData'
		dst = append(dst, 0, 0, 0, 0)
		{ // Static Field #11 'BaseFeePerGasLE'
			dst = append(dst, t.BaseFeePerGasLE[:32]...)
		}
		{ // Static Field #12 'BlockHash'
			dst = append(dst, t.BlockHash[:32]...)
		}
		{ // Static Field #13 'TransactionsRoot'
			dst = append(dst, t.TransactionsRoot[:32]...)
		}
		{ // Static Field #14 'WithdrawalsRoot'
			dst = append(dst, t.WithdrawalsRoot[:32]...)
		}
		{ // Dynamic Field #10 'ExtraData'
			binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
			vlen := len(t.ExtraData)
			if vlen > 32 {
				return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "Header.ExtraData")
			}
			dst = append(dst, t.ExtraData[:]...)
		}
	}
	return dst, nil
}

func (t *BuilderBid) marshalSSZView_BuilderBidDeneb(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(BuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Header'
	// Offset Field #1 'BlobKZGCommitments'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #2 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #3 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Dynamic Field #0 'Header'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		dstlen := len(dst)
		{ // Static Field #0 'ParentHash'
			dst = append(dst, t.ParentHash[:32]...)
		}
		{ // Static Field #1 'FeeRecipient'
			dst = append(dst, t.FeeRecipient[:20]...)
		}
		{ // Static Field #2 'StateRoot'
			dst = append(dst, t.StateRoot[:32]...)
		}
		{ // Static Field #3 'ReceiptsRoot'
			dst = append(dst, t.ReceiptsRoot[:32]...)
		}
		{ // Static Field #4 'LogsBloom'
			dst = append(dst, t.LogsBloom[:256]...)
		}
		{ // Static Field #5 'PrevRandao'
			dst = append(dst, t.PrevRandao[:32]...)
		}
		{ // Static Field #6 'BlockNumber'
			dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
		}
		{ // Static Field #7 'GasLimit'
			dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
		}
		{ // Static Field #8 'GasUsed'
			dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
		}
		{ // Static Field #9 'Timestamp'
			dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
		}
		// Offset Field #10 'ExtraData'
		dst = append(dst, 0, 0, 0, 0)
		{ // Static Field #11 'BaseFeePerGas'
			t := t.BaseFeePerGas
			if t == nil {
				t = new(uint256.Int)
			}
			dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
		}
		{ // Static Field #12 'BlockHash'
			dst = append(dst, t.BlockHash[:32]...)
		}
		{ // Static Field #13 'TransactionsRoot'
			dst = append(dst, t.TransactionsRoot[:32]...)
		}
		{ // Static Field #14 'WithdrawalsRoot'
			dst = append(dst, t.WithdrawalsRoot[:32]...)
		}
		{ // Static Field #15 'BlobGasUsed'
			dst = binary.LittleEndian.AppendUint64(dst, t.BlobGasUsed)
		}
		{ // Static Field #16 'ExcessBlobGas'
			dst = binary.LittleEndian.AppendUint64(dst, t.ExcessBlobGas)
		}
		{ // Dynamic Field #10 'ExtraData'
			binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
			vlen := len(t.ExtraData)
			if vlen > 32 {
				return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "Header.ExtraData")
			}
			dst = append(dst, t.ExtraData[:]...)
		}
	}
	{ // Dynamic Field #1 'BlobKZGCommitments'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.BlobKZGCommitments
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "BlobKZGCommitments")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *BuilderBid) marshalSSZView_BuilderBidElectra(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Header'
	// Offset Field #1 'BlobKZGCommitments'
	// Offset Field #2 'ExecutionRequests'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #3 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Static Field #4 'Pubkey'
		dst = append(dst, t.Pubkey[:48]...)
	}
	{ // Dynamic Field #0 'Header'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		dstlen := len(dst)
		{ // Static Field #0 'ParentHash'
			dst = append(dst, t.ParentHash[:32]...)
		}
		{ // Static Field #1 'FeeRecipient'
			dst = append(dst, t.FeeRecipient[:20]...)
		}
		{ // Static Field #2 'StateRoot'
			dst = append(dst, t.StateRoot[:32]...)
		}
		{ // Static Field #3 'ReceiptsRoot'
			dst = append(dst, t.ReceiptsRoot[:32]...)
		}
		{ // Static Field #4 'LogsBloom'
			dst = append(dst, t.LogsBloom[:256]...)
		}
		{ // Static Field #5 'PrevRandao'
			dst = append(dst, t.PrevRandao[:32]...)
		}
		{ // Static Field #6 'BlockNumber'
			dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
		}
		{ // Static Field #7 'GasLimit'
			dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
		}
		{ // Static Field #8 'GasUsed'
			dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
		}
		{ // Static Field #9 'Timestamp'
			dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
		}
		// Offset Field #10 'ExtraData'
		dst = append(dst, 0, 0, 0, 0)
		{ // Static Field #11 'BaseFeePerGas'
			t := t.BaseFeePerGas
			if t == nil {
				t = new(uint256.Int)
			}
			dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
		}
		{ // Static Field #12 'BlockHash'
			dst = append(dst, t.BlockHash[:32]...)
		}
		{ // Static Field #13 'TransactionsRoot'
			dst = append(dst, t.TransactionsRoot[:32]...)
		}
		{ // Static Field #14 'WithdrawalsRoot'
			dst = append(dst, t.WithdrawalsRoot[:32]...)
		}
		{ // Static Field #15 'BlobGasUsed'
			dst = binary.LittleEndian.AppendUint64(dst, t.BlobGasUsed)
		}
		{ // Static Field #16 'ExcessBlobGas'
			dst = binary.LittleEndian.AppendUint64(dst, t.ExcessBlobGas)
		}
		{ // Dynamic Field #10 'ExtraData'
			binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
			vlen := len(t.ExtraData)
			if vlen > 32 {
				return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "Header.ExtraData")
			}
			dst = append(dst, t.ExtraData[:]...)
		}
	}
	{ // Dynamic Field #1 'BlobKZGCommitments'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.BlobKZGCommitments
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "BlobKZGCommitments")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	{ // Dynamic Field #2 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		if t == nil {
			t = new(all.ExecutionRequests)
		}
		dstlen := len(dst)
		// Offset Field #0 'Deposits'
		// Offset Field #1 'Withdrawals'
		// Offset Field #2 'Consolidations'
		dst = append(dst, zeroBytes[:12]...)
		{ // Dynamic Field #0 'Deposits'
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
			t := t.Deposits
			vlen := len(t)
			if vlen > int(expr1) {
				return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "ExecutionRequests.Deposits")
			}
			for idx1 := range vlen {
				t := t[idx1]
				if t == nil {
					t = new(electra.DepositRequest)
				}
				if dst, err = t.MarshalSSZTo(dst); err != nil {
					return nil, sszutils.ErrorWithPathf(err, "ExecutionRequests.Deposits[%d]", idx1)
				}
			}
		}
		{ // Dynamic Field #1 'Withdrawals'
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
			t := t.Withdrawals
			vlen := len(t)
			if vlen > int(expr2) {
				return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr2)), "ExecutionRequests.Withdrawals")
			}
			for idx1 := range vlen {
				t := t[idx1]
				if t == nil {
					t = new(electra.WithdrawalRequest)
				}
				if dst, err = t.MarshalSSZTo(dst); err != nil {
					return nil, sszutils.ErrorWithPathf(err, "ExecutionRequests.Withdrawals[%d]", idx1)
				}
			}
		}
		{ // Dynamic Field #2 'Consolidations'
			binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
			t := t.Consolidations
			vlen := len(t)
			if vlen > int(expr3) {
				return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr3)), "ExecutionRequests.Consolidations")
			}
			for idx1 := range vlen {
				t := t[idx1]
				if t == nil {
					t = new(electra.ConsolidationRequest)
				}
				if dst, err = t.MarshalSSZTo(dst); err != nil {
					return nil, sszutils.ErrorWithPathf(err, "ExecutionRequests.Consolidations[%d]", idx1)
				}
			}
		}
	}
	return dst, nil
}

func (t *BuilderBid) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *BuilderBidBellatrix:
		return t.unmarshalSSZView_BuilderBidBellatrix
	case *BuilderBidCapella:
		return t.unmarshalSSZView_BuilderBidCapella
	case *BuilderBidDeneb:
		return t.unmarshalSSZView_BuilderBidDeneb
	case *BuilderBidElectra:
		return t.unmarshalSSZView_BuilderBidElectra
	}
	return nil
}
func (t *BuilderBid) unmarshalSSZView_BuilderBidBellatrix(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	// Field #0 'Header' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 84), "Header:o")
	}
	{ // Field #1 'Value' (static)
		buf := buf[4:36]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.Value = val1
	}
	{ // Field #2 'Pubkey' (static)
		buf := buf[36:84]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #0 'Header' (dynamic)
		buf := buf[offset0:]
		if t.Header == nil {
			t.Header = new(all.ExecutionPayloadHeader)
		}
		buflen := len(buf)
		if buflen < 536 {
			return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 536), "Header")
		}
		{ // Field #0 'ParentHash' (static)
			buf := buf[0:32]
			copy(t.Header.ParentHash[:], buf)
		}
		{ // Field #1 'FeeRecipient' (static)
			buf := buf[32:52]
			copy(t.Header.FeeRecipient[:], buf)
		}
		{ // Field #2 'StateRoot' (static)
			buf := buf[52:84]
			copy(t.Header.StateRoot[:], buf)
		}
		{ // Field #3 'ReceiptsRoot' (static)
			buf := buf[84:116]
			copy(t.Header.ReceiptsRoot[:], buf)
		}
		{ // Field #4 'LogsBloom' (static)
			buf := buf[116:372]
			copy(t.Header.LogsBloom[:], buf)
		}
		{ // Field #5 'PrevRandao' (static)
			buf := buf[372:404]
			copy(t.Header.PrevRandao[:], buf)
		}
		{ // Field #6 'BlockNumber' (static)
			buf := buf[404:412]
			t.Header.BlockNumber = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #7 'GasLimit' (static)
			buf := buf[412:420]
			t.Header.GasLimit = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #8 'GasUsed' (static)
			buf := buf[420:428]
			t.Header.GasUsed = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #9 'Timestamp' (static)
			buf := buf[428:436]
			t.Header.Timestamp = binary.LittleEndian.Uint64(buf)
		}
		// Field #10 'ExtraData' (offset)
		offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
		if offset10 != 536 {
			return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 536), "Header.ExtraData:o")
		}
		{ // Field #11 'BaseFeePerGasLE' (static)
			buf := buf[440:472]
			copy(t.Header.BaseFeePerGasLE[:], buf)
		}
		{ // Field #12 'BlockHash' (static)
			buf := buf[472:504]
			copy(t.Header.BlockHash[:], buf)
		}
		{ // Field #13 'TransactionsRoot' (static)
			buf := buf[504:536]
			copy(t.Header.TransactionsRoot[:], buf)
		}
		{ // Field #10 'ExtraData' (dynamic)
			buf := buf[offset10:]
			if len(buf) > 32 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 32), "Header.ExtraData")
			}
			t.Header.ExtraData = sszutils.ExpandSlice(t.Header.ExtraData, len(buf))
			copy(t.Header.ExtraData[:], buf)
		}
	}
	return nil
}

func (t *BuilderBid) unmarshalSSZView_BuilderBidCapella(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	// Field #0 'Header' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 84), "Header:o")
	}
	{ // Field #1 'Value' (static)
		buf := buf[4:36]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.Value = val1
	}
	{ // Field #2 'Pubkey' (static)
		buf := buf[36:84]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #0 'Header' (dynamic)
		buf := buf[offset0:]
		if t.Header == nil {
			t.Header = new(all.ExecutionPayloadHeader)
		}
		buflen := len(buf)
		if buflen < 568 {
			return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 568), "Header")
		}
		{ // Field #0 'ParentHash' (static)
			buf := buf[0:32]
			copy(t.Header.ParentHash[:], buf)
		}
		{ // Field #1 'FeeRecipient' (static)
			buf := buf[32:52]
			copy(t.Header.FeeRecipient[:], buf)
		}
		{ // Field #2 'StateRoot' (static)
			buf := buf[52:84]
			copy(t.Header.StateRoot[:], buf)
		}
		{ // Field #3 'ReceiptsRoot' (static)
			buf := buf[84:116]
			copy(t.Header.ReceiptsRoot[:], buf)
		}
		{ // Field #4 'LogsBloom' (static)
			buf := buf[116:372]
			copy(t.Header.LogsBloom[:], buf)
		}
		{ // Field #5 'PrevRandao' (static)
			buf := buf[372:404]
			copy(t.Header.PrevRandao[:], buf)
		}
		{ // Field #6 'BlockNumber' (static)
			buf := buf[404:412]
			t.Header.BlockNumber = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #7 'GasLimit' (static)
			buf := buf[412:420]
			t.Header.GasLimit = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #8 'GasUsed' (static)
			buf := buf[420:428]
			t.Header.GasUsed = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #9 'Timestamp' (static)
			buf := buf[428:436]
			t.Header.Timestamp = binary.LittleEndian.Uint64(buf)
		}
		// Field #10 'ExtraData' (offset)
		offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
		if offset10 != 568 {
			return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 568), "Header.ExtraData:o")
		}
		{ // Field #11 'BaseFeePerGasLE' (static)
			buf := buf[440:472]
			copy(t.Header.BaseFeePerGasLE[:], buf)
		}
		{ // Field #12 'BlockHash' (static)
			buf := buf[472:504]
			copy(t.Header.BlockHash[:], buf)
		}
		{ // Field #13 'TransactionsRoot' (static)
			buf := buf[504:536]
			copy(t.Header.TransactionsRoot[:], buf)
		}
		{ // Field #14 'WithdrawalsRoot' (static)
			buf := buf[536:568]
			copy(t.Header.WithdrawalsRoot[:], buf)
		}
		{ // Field #10 'ExtraData' (dynamic)
			buf := buf[offset10:]
			if len(buf) > 32 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 32), "Header.ExtraData")
			}
			t.Header.ExtraData = sszutils.ExpandSlice(t.Header.ExtraData, len(buf))
			copy(t.Header.ExtraData[:], buf)
		}
	}
	return nil
}

func (t *BuilderBid) unmarshalSSZView_BuilderBidDeneb(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 88 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 88)
	}
	// Field #0 'Header' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 88 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 88), "Header:o")
	}
	// Field #1 'BlobKZGCommitments' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "BlobKZGCommitments:o")
	}
	{ // Field #2 'Value' (static)
		buf := buf[8:40]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.Value = val1
	}
	{ // Field #3 'Pubkey' (static)
		buf := buf[40:88]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #0 'Header' (dynamic)
		buf := buf[offset0:offset1]
		if t.Header == nil {
			t.Header = new(all.ExecutionPayloadHeader)
		}
		buflen := len(buf)
		if buflen < 584 {
			return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 584), "Header")
		}
		{ // Field #0 'ParentHash' (static)
			buf := buf[0:32]
			copy(t.Header.ParentHash[:], buf)
		}
		{ // Field #1 'FeeRecipient' (static)
			buf := buf[32:52]
			copy(t.Header.FeeRecipient[:], buf)
		}
		{ // Field #2 'StateRoot' (static)
			buf := buf[52:84]
			copy(t.Header.StateRoot[:], buf)
		}
		{ // Field #3 'ReceiptsRoot' (static)
			buf := buf[84:116]
			copy(t.Header.ReceiptsRoot[:], buf)
		}
		{ // Field #4 'LogsBloom' (static)
			buf := buf[116:372]
			copy(t.Header.LogsBloom[:], buf)
		}
		{ // Field #5 'PrevRandao' (static)
			buf := buf[372:404]
			copy(t.Header.PrevRandao[:], buf)
		}
		{ // Field #6 'BlockNumber' (static)
			buf := buf[404:412]
			t.Header.BlockNumber = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #7 'GasLimit' (static)
			buf := buf[412:420]
			t.Header.GasLimit = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #8 'GasUsed' (static)
			buf := buf[420:428]
			t.Header.GasUsed = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #9 'Timestamp' (static)
			buf := buf[428:436]
			t.Header.Timestamp = binary.LittleEndian.Uint64(buf)
		}
		// Field #10 'ExtraData' (offset)
		offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
		if offset10 != 584 {
			return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 584), "Header.ExtraData:o")
		}
		{ // Field #11 'BaseFeePerGas' (static)
			buf := buf[440:472]
			val2 := t.Header.BaseFeePerGas
			if val2 == nil {
				val2 = new(uint256.Int)
			}
			sszutils.UnmarshalUint64Slice((*val2)[:4], buf)
			t.Header.BaseFeePerGas = val2
		}
		{ // Field #12 'BlockHash' (static)
			buf := buf[472:504]
			copy(t.Header.BlockHash[:], buf)
		}
		{ // Field #13 'TransactionsRoot' (static)
			buf := buf[504:536]
			copy(t.Header.TransactionsRoot[:], buf)
		}
		{ // Field #14 'WithdrawalsRoot' (static)
			buf := buf[536:568]
			copy(t.Header.WithdrawalsRoot[:], buf)
		}
		{ // Field #15 'BlobGasUsed' (static)
			buf := buf[568:576]
			t.Header.BlobGasUsed = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #16 'ExcessBlobGas' (static)
			buf := buf[576:584]
			t.Header.ExcessBlobGas = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #10 'ExtraData' (dynamic)
			buf := buf[offset10:]
			if len(buf) > 32 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 32), "Header.ExtraData")
			}
			t.Header.ExtraData = sszutils.ExpandSlice(t.Header.ExtraData, len(buf))
			copy(t.Header.ExtraData[:], buf)
		}
	}
	{ // Field #1 'BlobKZGCommitments' (dynamic)
		buf := buf[offset1:]
		val3 := t.BlobKZGCommitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "BlobKZGCommitments")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "BlobKZGCommitments")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val3[:itemCount], buf)
		t.BlobKZGCommitments = val3
	}
	return nil
}

func (t *BuilderBid) unmarshalSSZView_BuilderBidElectra(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 92 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 92)
	}
	// Field #0 'Header' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 92 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 92), "Header:o")
	}
	// Field #1 'BlobKZGCommitments' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "BlobKZGCommitments:o")
	}
	// Field #2 'ExecutionRequests' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "ExecutionRequests:o")
	}
	{ // Field #3 'Value' (static)
		buf := buf[12:44]
		val1 := t.Value
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.Value = val1
	}
	{ // Field #4 'Pubkey' (static)
		buf := buf[44:92]
		copy(t.Pubkey[:], buf)
	}
	{ // Field #0 'Header' (dynamic)
		buf := buf[offset0:offset1]
		if t.Header == nil {
			t.Header = new(all.ExecutionPayloadHeader)
		}
		buflen := len(buf)
		if buflen < 584 {
			return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 584), "Header")
		}
		{ // Field #0 'ParentHash' (static)
			buf := buf[0:32]
			copy(t.Header.ParentHash[:], buf)
		}
		{ // Field #1 'FeeRecipient' (static)
			buf := buf[32:52]
			copy(t.Header.FeeRecipient[:], buf)
		}
		{ // Field #2 'StateRoot' (static)
			buf := buf[52:84]
			copy(t.Header.StateRoot[:], buf)
		}
		{ // Field #3 'ReceiptsRoot' (static)
			buf := buf[84:116]
			copy(t.Header.ReceiptsRoot[:], buf)
		}
		{ // Field #4 'LogsBloom' (static)
			buf := buf[116:372]
			copy(t.Header.LogsBloom[:], buf)
		}
		{ // Field #5 'PrevRandao' (static)
			buf := buf[372:404]
			copy(t.Header.PrevRandao[:], buf)
		}
		{ // Field #6 'BlockNumber' (static)
			buf := buf[404:412]
			t.Header.BlockNumber = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #7 'GasLimit' (static)
			buf := buf[412:420]
			t.Header.GasLimit = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #8 'GasUsed' (static)
			buf := buf[420:428]
			t.Header.GasUsed = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #9 'Timestamp' (static)
			buf := buf[428:436]
			t.Header.Timestamp = binary.LittleEndian.Uint64(buf)
		}
		// Field #10 'ExtraData' (offset)
		offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
		if offset10 != 584 {
			return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 584), "Header.ExtraData:o")
		}
		{ // Field #11 'BaseFeePerGas' (static)
			buf := buf[440:472]
			val2 := t.Header.BaseFeePerGas
			if val2 == nil {
				val2 = new(uint256.Int)
			}
			sszutils.UnmarshalUint64Slice((*val2)[:4], buf)
			t.Header.BaseFeePerGas = val2
		}
		{ // Field #12 'BlockHash' (static)
			buf := buf[472:504]
			copy(t.Header.BlockHash[:], buf)
		}
		{ // Field #13 'TransactionsRoot' (static)
			buf := buf[504:536]
			copy(t.Header.TransactionsRoot[:], buf)
		}
		{ // Field #14 'WithdrawalsRoot' (static)
			buf := buf[536:568]
			copy(t.Header.WithdrawalsRoot[:], buf)
		}
		{ // Field #15 'BlobGasUsed' (static)
			buf := buf[568:576]
			t.Header.BlobGasUsed = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #16 'ExcessBlobGas' (static)
			buf := buf[576:584]
			t.Header.ExcessBlobGas = binary.LittleEndian.Uint64(buf)
		}
		{ // Field #10 'ExtraData' (dynamic)
			buf := buf[offset10:]
			if len(buf) > 32 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 32), "Header.ExtraData")
			}
			t.Header.ExtraData = sszutils.ExpandSlice(t.Header.ExtraData, len(buf))
			copy(t.Header.ExtraData[:], buf)
		}
	}
	{ // Field #1 'BlobKZGCommitments' (dynamic)
		buf := buf[offset1:offset2]
		val3 := t.BlobKZGCommitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "BlobKZGCommitments")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "BlobKZGCommitments")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val3[:itemCount], buf)
		t.BlobKZGCommitments = val3
	}
	{ // Field #2 'ExecutionRequests' (dynamic)
		buf := buf[offset2:]
		if t.ExecutionRequests == nil {
			t.ExecutionRequests = new(all.ExecutionRequests)
		}
		buflen := len(buf)
		if buflen < 12 {
			return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 12), "ExecutionRequests")
		}
		// Field #0 'Deposits' (offset)
		offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
		if offset0 != 12 {
			return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "ExecutionRequests.Deposits:o")
		}
		// Field #1 'Withdrawals' (offset)
		offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
		if offset1 < offset0 || offset1 > buflen {
			return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "ExecutionRequests.Withdrawals:o")
		}
		// Field #2 'Consolidations' (offset)
		offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
		if offset2 < offset1 || offset2 > buflen {
			return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "ExecutionRequests.Consolidations:o")
		}
		{ // Field #0 'Deposits' (dynamic)
			buf := buf[offset0:offset1]
			val4 := t.ExecutionRequests.Deposits
			itemCount := len(buf) / 192
			if len(buf)%192 != 0 {
				return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 192), "ExecutionRequests.Deposits")
			}
			if itemCount > int(expr1) {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "ExecutionRequests.Deposits")
			}
			val4 = sszutils.ExpandSlice(val4, itemCount)
			for idx1 := range itemCount {
				if val4[idx1] == nil {
					val4[idx1] = new(electra.DepositRequest)
				}
				buf := buf[192*idx1 : 192*(idx1+1)]
				if err = val4[idx1].UnmarshalSSZ(buf); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Deposits[%d]", idx1)
				}
			}
			t.ExecutionRequests.Deposits = val4
		}
		{ // Field #1 'Withdrawals' (dynamic)
			buf := buf[offset1:offset2]
			val5 := t.ExecutionRequests.Withdrawals
			itemCount := len(buf) / 76
			if len(buf)%76 != 0 {
				return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 76), "ExecutionRequests.Withdrawals")
			}
			if itemCount > int(expr2) {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr2)), "ExecutionRequests.Withdrawals")
			}
			val5 = sszutils.ExpandSlice(val5, itemCount)
			for idx1 := range itemCount {
				if val5[idx1] == nil {
					val5[idx1] = new(electra.WithdrawalRequest)
				}
				buf := buf[76*idx1 : 76*(idx1+1)]
				if err = val5[idx1].UnmarshalSSZ(buf); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Withdrawals[%d]", idx1)
				}
			}
			t.ExecutionRequests.Withdrawals = val5
		}
		{ // Field #2 'Consolidations' (dynamic)
			buf := buf[offset2:]
			val6 := t.ExecutionRequests.Consolidations
			itemCount := len(buf) / 116
			if len(buf)%116 != 0 {
				return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 116), "ExecutionRequests.Consolidations")
			}
			if itemCount > int(expr3) {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr3)), "ExecutionRequests.Consolidations")
			}
			val6 = sszutils.ExpandSlice(val6, itemCount)
			for idx1 := range itemCount {
				if val6[idx1] == nil {
					val6[idx1] = new(electra.ConsolidationRequest)
				}
				buf := buf[116*idx1 : 116*(idx1+1)]
				if err = val6[idx1].UnmarshalSSZ(buf); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Consolidations[%d]", idx1)
				}
			}
			t.ExecutionRequests.Consolidations = val6
		}
	}
	return nil
}

func (t *BuilderBid) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *BuilderBidBellatrix:
		return t.sizeSSZView_BuilderBidBellatrix
	case *BuilderBidCapella:
		return t.sizeSSZView_BuilderBidCapella
	case *BuilderBidDeneb:
		return t.sizeSSZView_BuilderBidDeneb
	case *BuilderBidElectra:
		return t.sizeSSZView_BuilderBidElectra
	}
	return nil
}
func (t *BuilderBid) sizeSSZView_BuilderBidBellatrix(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BuilderBid)
	}
	// Field #0 'Header' offset (4 bytes)
	// Field #1 'Value' static (32 bytes)
	// Field #2 'Pubkey' static (48 bytes)
	size += 84
	{ // Dynamic field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		// Field #0 'ParentHash' static (32 bytes)
		// Field #1 'FeeRecipient' static (20 bytes)
		// Field #2 'StateRoot' static (32 bytes)
		// Field #3 'ReceiptsRoot' static (32 bytes)
		// Field #4 'LogsBloom' static (256 bytes)
		// Field #5 'PrevRandao' static (32 bytes)
		// Field #6 'BlockNumber' static (8 bytes)
		// Field #7 'GasLimit' static (8 bytes)
		// Field #8 'GasUsed' static (8 bytes)
		// Field #9 'Timestamp' static (8 bytes)
		// Field #10 'ExtraData' offset (4 bytes)
		// Field #11 'BaseFeePerGasLE' static (32 bytes)
		// Field #12 'BlockHash' static (32 bytes)
		// Field #13 'TransactionsRoot' static (32 bytes)
		size += 536
		{ // Dynamic field #10 'ExtraData'
			size += len(t.ExtraData)
		}
	}
	return size
}

func (t *BuilderBid) sizeSSZView_BuilderBidCapella(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BuilderBid)
	}
	// Field #0 'Header' offset (4 bytes)
	// Field #1 'Value' static (32 bytes)
	// Field #2 'Pubkey' static (48 bytes)
	size += 84
	{ // Dynamic field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		// Field #0 'ParentHash' static (32 bytes)
		// Field #1 'FeeRecipient' static (20 bytes)
		// Field #2 'StateRoot' static (32 bytes)
		// Field #3 'ReceiptsRoot' static (32 bytes)
		// Field #4 'LogsBloom' static (256 bytes)
		// Field #5 'PrevRandao' static (32 bytes)
		// Field #6 'BlockNumber' static (8 bytes)
		// Field #7 'GasLimit' static (8 bytes)
		// Field #8 'GasUsed' static (8 bytes)
		// Field #9 'Timestamp' static (8 bytes)
		// Field #10 'ExtraData' offset (4 bytes)
		// Field #11 'BaseFeePerGasLE' static (32 bytes)
		// Field #12 'BlockHash' static (32 bytes)
		// Field #13 'TransactionsRoot' static (32 bytes)
		// Field #14 'WithdrawalsRoot' static (32 bytes)
		size += 568
		{ // Dynamic field #10 'ExtraData'
			size += len(t.ExtraData)
		}
	}
	return size
}

func (t *BuilderBid) sizeSSZView_BuilderBidDeneb(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BuilderBid)
	}
	// Field #0 'Header' offset (4 bytes)
	// Field #1 'BlobKZGCommitments' offset (4 bytes)
	// Field #2 'Value' static (32 bytes)
	// Field #3 'Pubkey' static (48 bytes)
	size += 88
	{ // Dynamic field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		// Field #0 'ParentHash' static (32 bytes)
		// Field #1 'FeeRecipient' static (20 bytes)
		// Field #2 'StateRoot' static (32 bytes)
		// Field #3 'ReceiptsRoot' static (32 bytes)
		// Field #4 'LogsBloom' static (256 bytes)
		// Field #5 'PrevRandao' static (32 bytes)
		// Field #6 'BlockNumber' static (8 bytes)
		// Field #7 'GasLimit' static (8 bytes)
		// Field #8 'GasUsed' static (8 bytes)
		// Field #9 'Timestamp' static (8 bytes)
		// Field #10 'ExtraData' offset (4 bytes)
		// Field #11 'BaseFeePerGas' static (32 bytes)
		// Field #12 'BlockHash' static (32 bytes)
		// Field #13 'TransactionsRoot' static (32 bytes)
		// Field #14 'WithdrawalsRoot' static (32 bytes)
		// Field #15 'BlobGasUsed' static (8 bytes)
		// Field #16 'ExcessBlobGas' static (8 bytes)
		size += 584
		{ // Dynamic field #10 'ExtraData'
			size += len(t.ExtraData)
		}
	}
	{ // Dynamic field #1 'BlobKZGCommitments'
		size += len(t.BlobKZGCommitments) * 48
	}
	return size
}

func (t *BuilderBid) sizeSSZView_BuilderBidElectra(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BuilderBid)
	}
	// Field #0 'Header' offset (4 bytes)
	// Field #1 'BlobKZGCommitments' offset (4 bytes)
	// Field #2 'ExecutionRequests' offset (4 bytes)
	// Field #3 'Value' static (32 bytes)
	// Field #4 'Pubkey' static (48 bytes)
	size += 92
	{ // Dynamic field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		// Field #0 'ParentHash' static (32 bytes)
		// Field #1 'FeeRecipient' static (20 bytes)
		// Field #2 'StateRoot' static (32 bytes)
		// Field #3 'ReceiptsRoot' static (32 bytes)
		// Field #4 'LogsBloom' static (256 bytes)
		// Field #5 'PrevRandao' static (32 bytes)
		// Field #6 'BlockNumber' static (8 bytes)
		// Field #7 'GasLimit' static (8 bytes)
		// Field #8 'GasUsed' static (8 bytes)
		// Field #9 'Timestamp' static (8 bytes)
		// Field #10 'ExtraData' offset (4 bytes)
		// Field #11 'BaseFeePerGas' static (32 bytes)
		// Field #12 'BlockHash' static (32 bytes)
		// Field #13 'TransactionsRoot' static (32 bytes)
		// Field #14 'WithdrawalsRoot' static (32 bytes)
		// Field #15 'BlobGasUsed' static (8 bytes)
		// Field #16 'ExcessBlobGas' static (8 bytes)
		size += 584
		{ // Dynamic field #10 'ExtraData'
			size += len(t.ExtraData)
		}
	}
	{ // Dynamic field #1 'BlobKZGCommitments'
		size += len(t.BlobKZGCommitments) * 48
	}
	{ // Dynamic field #2 'ExecutionRequests'
		t := t.ExecutionRequests
		if t == nil {
			t = new(all.ExecutionRequests)
		}
		// Field #0 'Deposits' offset (4 bytes)
		// Field #1 'Withdrawals' offset (4 bytes)
		// Field #2 'Consolidations' offset (4 bytes)
		size += 12
		{ // Dynamic field #0 'Deposits'
			size += len(t.Deposits) * 192
		}
		{ // Dynamic field #1 'Withdrawals'
			size += len(t.Withdrawals) * 76
		}
		{ // Dynamic field #2 'Consolidations'
			size += len(t.Consolidations) * 116
		}
	}
	return size
}

func (t *BuilderBid) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *BuilderBidBellatrix:
		return t.hashTreeRootView_BuilderBidBellatrix
	case *BuilderBidCapella:
		return t.hashTreeRootView_BuilderBidCapella
	case *BuilderBidDeneb:
		return t.hashTreeRootView_BuilderBidDeneb
	case *BuilderBidElectra:
		return t.hashTreeRootView_BuilderBidElectra
	}
	return nil
}
func (t *BuilderBid) hashTreeRootView_BuilderBidBellatrix(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		idx := hh.StartTree(sszutils.TreeTypeNone)
		{ // Field #0 'ParentHash'
			hh.PutBytes(t.ParentHash[:32])
		}
		{ // Field #1 'FeeRecipient'
			hh.PutBytes(t.FeeRecipient[:20])
		}
		{ // Field #2 'StateRoot'
			hh.PutBytes(t.StateRoot[:32])
		}
		{ // Field #3 'ReceiptsRoot'
			hh.PutBytes(t.ReceiptsRoot[:32])
		}
		{ // Field #4 'LogsBloom'
			hh.PutBytes(t.LogsBloom[:256])
		}
		{ // Field #5 'PrevRandao'
			hh.PutBytes(t.PrevRandao[:32])
		}
		{ // Field #6 'BlockNumber'
			hh.PutUint64(t.BlockNumber)
		}
		{ // Field #7 'GasLimit'
			hh.PutUint64(t.GasLimit)
		}
		{ // Field #8 'GasUsed'
			hh.PutUint64(t.GasUsed)
		}
		{ // Field #9 'Timestamp'
			hh.PutUint64(t.Timestamp)
		}
		{ // Field #10 'ExtraData'
			vlen := uint64(len(t.ExtraData))
			if vlen > 32 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "Header.ExtraData")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t.ExtraData[:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 1))
		}
		{ // Field #11 'BaseFeePerGasLE'
			hh.PutBytes(t.BaseFeePerGasLE[:32])
		}
		{ // Field #12 'BlockHash'
			hh.PutBytes(t.BlockHash[:32])
		}
		{ // Field #13 'TransactionsRoot'
			hh.PutBytes(t.TransactionsRoot[:32])
		}
		hh.Merkleize(idx)
	}
	{ // Field #1 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "Value")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BuilderBid) hashTreeRootView_BuilderBidCapella(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		idx := hh.StartTree(sszutils.TreeTypeNone)
		{ // Field #0 'ParentHash'
			hh.PutBytes(t.ParentHash[:32])
		}
		{ // Field #1 'FeeRecipient'
			hh.PutBytes(t.FeeRecipient[:20])
		}
		{ // Field #2 'StateRoot'
			hh.PutBytes(t.StateRoot[:32])
		}
		{ // Field #3 'ReceiptsRoot'
			hh.PutBytes(t.ReceiptsRoot[:32])
		}
		{ // Field #4 'LogsBloom'
			hh.PutBytes(t.LogsBloom[:256])
		}
		{ // Field #5 'PrevRandao'
			hh.PutBytes(t.PrevRandao[:32])
		}
		{ // Field #6 'BlockNumber'
			hh.PutUint64(t.BlockNumber)
		}
		{ // Field #7 'GasLimit'
			hh.PutUint64(t.GasLimit)
		}
		{ // Field #8 'GasUsed'
			hh.PutUint64(t.GasUsed)
		}
		{ // Field #9 'Timestamp'
			hh.PutUint64(t.Timestamp)
		}
		{ // Field #10 'ExtraData'
			vlen := uint64(len(t.ExtraData))
			if vlen > 32 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "Header.ExtraData")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t.ExtraData[:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 1))
		}
		{ // Field #11 'BaseFeePerGasLE'
			hh.PutBytes(t.BaseFeePerGasLE[:32])
		}
		{ // Field #12 'BlockHash'
			hh.PutBytes(t.BlockHash[:32])
		}
		{ // Field #13 'TransactionsRoot'
			hh.PutBytes(t.TransactionsRoot[:32])
		}
		{ // Field #14 'WithdrawalsRoot'
			hh.PutBytes(t.WithdrawalsRoot[:32])
		}
		hh.Merkleize(idx)
	}
	{ // Field #1 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "Value")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BuilderBid) hashTreeRootView_BuilderBidDeneb(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(BuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		idx := hh.StartTree(sszutils.TreeTypeNone)
		{ // Field #0 'ParentHash'
			hh.PutBytes(t.ParentHash[:32])
		}
		{ // Field #1 'FeeRecipient'
			hh.PutBytes(t.FeeRecipient[:20])
		}
		{ // Field #2 'StateRoot'
			hh.PutBytes(t.StateRoot[:32])
		}
		{ // Field #3 'ReceiptsRoot'
			hh.PutBytes(t.ReceiptsRoot[:32])
		}
		{ // Field #4 'LogsBloom'
			hh.PutBytes(t.LogsBloom[:256])
		}
		{ // Field #5 'PrevRandao'
			hh.PutBytes(t.PrevRandao[:32])
		}
		{ // Field #6 'BlockNumber'
			hh.PutUint64(t.BlockNumber)
		}
		{ // Field #7 'GasLimit'
			hh.PutUint64(t.GasLimit)
		}
		{ // Field #8 'GasUsed'
			hh.PutUint64(t.GasUsed)
		}
		{ // Field #9 'Timestamp'
			hh.PutUint64(t.Timestamp)
		}
		{ // Field #10 'ExtraData'
			vlen := uint64(len(t.ExtraData))
			if vlen > 32 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "Header.ExtraData")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t.ExtraData[:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 1))
		}
		{ // Field #11 'BaseFeePerGas'
			t := t.BaseFeePerGas
			if t == nil {
				t = new(uint256.Int)
			}
			if root, err := t.HashTreeRoot(); err != nil {
				return sszutils.ErrorWithPath(err, "Header.BaseFeePerGas")
			} else {
				hh.AppendBytes32(root[:])
			}
		}
		{ // Field #12 'BlockHash'
			hh.PutBytes(t.BlockHash[:32])
		}
		{ // Field #13 'TransactionsRoot'
			hh.PutBytes(t.TransactionsRoot[:32])
		}
		{ // Field #14 'WithdrawalsRoot'
			hh.PutBytes(t.WithdrawalsRoot[:32])
		}
		{ // Field #15 'BlobGasUsed'
			hh.PutUint64(t.BlobGasUsed)
		}
		{ // Field #16 'ExcessBlobGas'
			hh.PutUint64(t.ExcessBlobGas)
		}
		hh.Merkleize(idx)
	}
	{ // Field #1 'BlobKZGCommitments'
		t := t.BlobKZGCommitments
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "BlobKZGCommitments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "Value")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #3 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BuilderBid) hashTreeRootView_BuilderBidElectra(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(BuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Header'
		t := t.Header
		if t == nil {
			t = new(all.ExecutionPayloadHeader)
		}
		idx := hh.StartTree(sszutils.TreeTypeNone)
		{ // Field #0 'ParentHash'
			hh.PutBytes(t.ParentHash[:32])
		}
		{ // Field #1 'FeeRecipient'
			hh.PutBytes(t.FeeRecipient[:20])
		}
		{ // Field #2 'StateRoot'
			hh.PutBytes(t.StateRoot[:32])
		}
		{ // Field #3 'ReceiptsRoot'
			hh.PutBytes(t.ReceiptsRoot[:32])
		}
		{ // Field #4 'LogsBloom'
			hh.PutBytes(t.LogsBloom[:256])
		}
		{ // Field #5 'PrevRandao'
			hh.PutBytes(t.PrevRandao[:32])
		}
		{ // Field #6 'BlockNumber'
			hh.PutUint64(t.BlockNumber)
		}
		{ // Field #7 'GasLimit'
			hh.PutUint64(t.GasLimit)
		}
		{ // Field #8 'GasUsed'
			hh.PutUint64(t.GasUsed)
		}
		{ // Field #9 'Timestamp'
			hh.PutUint64(t.Timestamp)
		}
		{ // Field #10 'ExtraData'
			vlen := uint64(len(t.ExtraData))
			if vlen > 32 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "Header.ExtraData")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t.ExtraData[:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 1))
		}
		{ // Field #11 'BaseFeePerGas'
			t := t.BaseFeePerGas
			if t == nil {
				t = new(uint256.Int)
			}
			if root, err := t.HashTreeRoot(); err != nil {
				return sszutils.ErrorWithPath(err, "Header.BaseFeePerGas")
			} else {
				hh.AppendBytes32(root[:])
			}
		}
		{ // Field #12 'BlockHash'
			hh.PutBytes(t.BlockHash[:32])
		}
		{ // Field #13 'TransactionsRoot'
			hh.PutBytes(t.TransactionsRoot[:32])
		}
		{ // Field #14 'WithdrawalsRoot'
			hh.PutBytes(t.WithdrawalsRoot[:32])
		}
		{ // Field #15 'BlobGasUsed'
			hh.PutUint64(t.BlobGasUsed)
		}
		{ // Field #16 'ExcessBlobGas'
			hh.PutUint64(t.ExcessBlobGas)
		}
		hh.Merkleize(idx)
	}
	{ // Field #1 'BlobKZGCommitments'
		t := t.BlobKZGCommitments
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "BlobKZGCommitments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'ExecutionRequests'
		t := t.ExecutionRequests
		if t == nil {
			t = new(all.ExecutionRequests)
		}
		idx := hh.StartTree(sszutils.TreeTypeNone)
		{ // Field #0 'Deposits'
			t := t.Deposits
			vlen := uint64(len(t))
			if vlen > expr1 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "ExecutionRequests.Deposits")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			for idx1 := range int(vlen) {
				t := t[idx1]
				if t == nil {
					t = new(electra.DepositRequest)
				}
				if err := t.HashTreeRootWith(hh); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Deposits[%d]", idx1)
				}
				if (idx1+1)%256 == 0 {
					hh.Collapse()
				}
			}
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
		}
		{ // Field #1 'Withdrawals'
			t := t.Withdrawals
			vlen := uint64(len(t))
			if vlen > expr2 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr2), "ExecutionRequests.Withdrawals")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			for idx1 := range int(vlen) {
				t := t[idx1]
				if t == nil {
					t = new(electra.WithdrawalRequest)
				}
				if err := t.HashTreeRootWith(hh); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Withdrawals[%d]", idx1)
				}
				if (idx1+1)%256 == 0 {
					hh.Collapse()
				}
			}
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 32))
		}
		{ // Field #2 'Consolidations'
			t := t.Consolidations
			vlen := uint64(len(t))
			if vlen > expr3 {
				return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr3), "ExecutionRequests.Consolidations")
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			for idx1 := range int(vlen) {
				t := t[idx1]
				if t == nil {
					t = new(electra.ConsolidationRequest)
				}
				if err := t.HashTreeRootWith(hh); err != nil {
					return sszutils.ErrorWithPathf(err, "ExecutionRequests.Consolidations[%d]", idx1)
				}
				if (idx1+1)%256 == 0 {
					hh.Collapse()
				}
			}
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr3, vlen, 32))
		}
		hh.Merkleize(idx)
	}
	{ // Field #3 'Value'
		t := t.Value
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "Value")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #4 'Pubkey'
		hh.PutBytes(t.Pubkey[:48])
	}
	hh.Merkleize(idx)
	return nil
}
