// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: d3673c91ba4e5ff4c6ee7993cddefe27c8231596c9fb40c59ced68c903d462e0
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package types

import (
	"encoding/binary"

	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*SignedBuilderBidBellatrix](`ssz-static:"false"`)
var _ = sszutils.Annotate[*SignedBuilderBidCapella](`ssz-static:"false"`)
var _ = sszutils.Annotate[*SignedBuilderBidDeneb](`ssz-static:"false"`)
var _ = sszutils.Annotate[*SignedBuilderBidElectra](`ssz-static:"false"`)

func (t *SignedBuilderBid) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *SignedBuilderBidBellatrix:
		return t.marshalSSZView_SignedBuilderBidBellatrix
	case *SignedBuilderBidCapella:
		return t.marshalSSZView_SignedBuilderBidCapella
	case *SignedBuilderBidDeneb:
		return t.marshalSSZView_SignedBuilderBidDeneb
	case *SignedBuilderBidElectra:
		return t.marshalSSZView_SignedBuilderBidElectra
	}
	return nil
}
func (t *SignedBuilderBid) marshalSSZView_SignedBuilderBidBellatrix(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BuilderBid)
		}
		if viewFn := t.MarshalSSZDynView((*BuilderBidBellatrix)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBuilderBid) marshalSSZView_SignedBuilderBidCapella(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BuilderBid)
		}
		if viewFn := t.MarshalSSZDynView((*BuilderBidCapella)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBuilderBid) marshalSSZView_SignedBuilderBidDeneb(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BuilderBid)
		}
		if viewFn := t.MarshalSSZDynView((*BuilderBidDeneb)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBuilderBid) marshalSSZView_SignedBuilderBidElectra(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBuilderBid)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BuilderBid)
		}
		if viewFn := t.MarshalSSZDynView((*BuilderBidElectra)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBuilderBid) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *SignedBuilderBidBellatrix:
		return t.unmarshalSSZView_SignedBuilderBidBellatrix
	case *SignedBuilderBidCapella:
		return t.unmarshalSSZView_SignedBuilderBidCapella
	case *SignedBuilderBidDeneb:
		return t.unmarshalSSZView_SignedBuilderBidDeneb
	case *SignedBuilderBidElectra:
		return t.unmarshalSSZView_SignedBuilderBidElectra
	}
	return nil
}
func (t *SignedBuilderBid) unmarshalSSZView_SignedBuilderBidBellatrix(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BuilderBid)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*BuilderBidBellatrix)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBuilderBid) unmarshalSSZView_SignedBuilderBidCapella(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BuilderBid)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*BuilderBidCapella)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBuilderBid) unmarshalSSZView_SignedBuilderBidDeneb(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BuilderBid)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*BuilderBidDeneb)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBuilderBid) unmarshalSSZView_SignedBuilderBidElectra(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BuilderBid)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*BuilderBidElectra)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBuilderBid) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *SignedBuilderBidBellatrix:
		return t.sizeSSZView_SignedBuilderBidBellatrix
	case *SignedBuilderBidCapella:
		return t.sizeSSZView_SignedBuilderBidCapella
	case *SignedBuilderBidDeneb:
		return t.sizeSSZView_SignedBuilderBidDeneb
	case *SignedBuilderBidElectra:
		return t.sizeSSZView_SignedBuilderBidElectra
	}
	return nil
}
func (t *SignedBuilderBid) sizeSSZView_SignedBuilderBidBellatrix(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBuilderBid)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*BuilderBidBellatrix)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBuilderBid) sizeSSZView_SignedBuilderBidCapella(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBuilderBid)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*BuilderBidCapella)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBuilderBid) sizeSSZView_SignedBuilderBidDeneb(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBuilderBid)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*BuilderBidDeneb)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBuilderBid) sizeSSZView_SignedBuilderBidElectra(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBuilderBid)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*BuilderBidElectra)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBuilderBid) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *SignedBuilderBidBellatrix:
		return t.hashTreeRootView_SignedBuilderBidBellatrix
	case *SignedBuilderBidCapella:
		return t.hashTreeRootView_SignedBuilderBidCapella
	case *SignedBuilderBidDeneb:
		return t.hashTreeRootView_SignedBuilderBidDeneb
	case *SignedBuilderBidElectra:
		return t.hashTreeRootView_SignedBuilderBidElectra
	}
	return nil
}
func (t *SignedBuilderBid) hashTreeRootView_SignedBuilderBidBellatrix(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BuilderBid)
		}
		if viewFn := t.HashTreeRootWithDynView((*BuilderBidBellatrix)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBuilderBid) hashTreeRootView_SignedBuilderBidCapella(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BuilderBid)
		}
		if viewFn := t.HashTreeRootWithDynView((*BuilderBidCapella)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBuilderBid) hashTreeRootView_SignedBuilderBidDeneb(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BuilderBid)
		}
		if viewFn := t.HashTreeRootWithDynView((*BuilderBidDeneb)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBuilderBid) hashTreeRootView_SignedBuilderBidElectra(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBuilderBid)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BuilderBid)
		}
		if viewFn := t.HashTreeRootWithDynView((*BuilderBidElectra)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
